apiVersion: cache.geiser.cloud/v1alpha1
kind: Redis
metadata:
  name: redis-sample2
  namespace: default
  labels:
    app.kubernetes.io/name: redis-sample2
    app.kubernetes.io/managed-by: kustomize
spec:
  # ────────────── scale ──────────────
  replicas: 3

  # ───────────── image ──────────────
  image: bitnami/redis:7.0
